# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'

      - name: Build
        run: hugo --minify

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2  # Updated to use version 2
        with:
          workload_identity_provider: 'projects/1073125370900/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'service-account-static-website@kvm-nested-vm.iam.gserviceaccount.com'

      - name: Upload files to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'public'
          destination: 'gs://cs1660-static-website'  # Ensure this is the correct GCS bucket path
          parent: false
