name: Deploy Static Website

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull request events to the main branch

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -alh  # Optional step to list files for debugging

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/1073125370900/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'service-account-static-website@kvm-nested-vm.iam.gserviceaccount.com'

      - name: Upload files to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'public'  # Make sure this is the directory where your site's files are located
          destination: 'gs://cs1660-static-website'  # Update this with your actual GCS bucket name
          parent: false
