name: Deploy Static Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: List all files and directories
        run: ls -alh

      - name: Setup and Build Project
        run: |
          mkdir -p public  # Ensure the directory exists
          cp -r src/* public/
          echo "Populate your public directory here"

      - name: List contents of the public directory
        run: ls -alh public/

      - name: Upload Files to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'public'
          destination: 'gs://cs1660-static-website'
          parent: false
          process_gcloudignore: false  # Assuming you don't need to ignore files
