name: Static Site

on:
  push:
    branches:
      - master  # Set a branch to deploy
      - gha-service-account
  pull_request:
    branches: [ "master", "gha-service-account" ]  # Specify branches for pull requests if needed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup and Build Project  # Assuming you need to build or copy files
        run: |
          mkdir -p public
          echo "Building project or copying files to public directory"
          # Add your build or setup commands here

      - name: List contents of the public directory
        run: ls -alh public/

      - name: Upload Files to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: public
          destination: gs://cs1660-static-website
          parent: false

